# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.context import Context  # noqa: F401,E501
from swagger_server import util


class ServiceInstanceProvisionRequestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, service_id: str=None, plan_id: str=None, context: Context=None, organization_guid: str=None, space_guid: str=None, parameters: Object=None):  # noqa: E501
        """ServiceInstanceProvisionRequestBody - a model defined in Swagger

        :param service_id: The service_id of this ServiceInstanceProvisionRequestBody.  # noqa: E501
        :type service_id: str
        :param plan_id: The plan_id of this ServiceInstanceProvisionRequestBody.  # noqa: E501
        :type plan_id: str
        :param context: The context of this ServiceInstanceProvisionRequestBody.  # noqa: E501
        :type context: Context
        :param organization_guid: The organization_guid of this ServiceInstanceProvisionRequestBody.  # noqa: E501
        :type organization_guid: str
        :param space_guid: The space_guid of this ServiceInstanceProvisionRequestBody.  # noqa: E501
        :type space_guid: str
        :param parameters: The parameters of this ServiceInstanceProvisionRequestBody.  # noqa: E501
        :type parameters: Object
        """
        self.swagger_types = {
            'service_id': str,
            'plan_id': str,
            'context': Context,
            'organization_guid': str,
            'space_guid': str,
            'parameters': Object
        }

        self.attribute_map = {
            'service_id': 'service_id',
            'plan_id': 'plan_id',
            'context': 'context',
            'organization_guid': 'organization_guid',
            'space_guid': 'space_guid',
            'parameters': 'parameters'
        }
        self._service_id = service_id
        self._plan_id = plan_id
        self._context = context
        self._organization_guid = organization_guid
        self._space_guid = space_guid
        self._parameters = parameters

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceInstanceProvisionRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceInstanceProvisionRequestBody of this ServiceInstanceProvisionRequestBody.  # noqa: E501
        :rtype: ServiceInstanceProvisionRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_id(self) -> str:
        """Gets the service_id of this ServiceInstanceProvisionRequestBody.


        :return: The service_id of this ServiceInstanceProvisionRequestBody.
        :rtype: str
        """
        return self._service_id

    @service_id.setter
    def service_id(self, service_id: str):
        """Sets the service_id of this ServiceInstanceProvisionRequestBody.


        :param service_id: The service_id of this ServiceInstanceProvisionRequestBody.
        :type service_id: str
        """
        if service_id is None:
            raise ValueError("Invalid value for `service_id`, must not be `None`")  # noqa: E501

        self._service_id = service_id

    @property
    def plan_id(self) -> str:
        """Gets the plan_id of this ServiceInstanceProvisionRequestBody.


        :return: The plan_id of this ServiceInstanceProvisionRequestBody.
        :rtype: str
        """
        return self._plan_id

    @plan_id.setter
    def plan_id(self, plan_id: str):
        """Sets the plan_id of this ServiceInstanceProvisionRequestBody.


        :param plan_id: The plan_id of this ServiceInstanceProvisionRequestBody.
        :type plan_id: str
        """
        if plan_id is None:
            raise ValueError("Invalid value for `plan_id`, must not be `None`")  # noqa: E501

        self._plan_id = plan_id

    @property
    def context(self) -> Context:
        """Gets the context of this ServiceInstanceProvisionRequestBody.


        :return: The context of this ServiceInstanceProvisionRequestBody.
        :rtype: Context
        """
        return self._context

    @context.setter
    def context(self, context: Context):
        """Sets the context of this ServiceInstanceProvisionRequestBody.


        :param context: The context of this ServiceInstanceProvisionRequestBody.
        :type context: Context
        """

        self._context = context

    @property
    def organization_guid(self) -> str:
        """Gets the organization_guid of this ServiceInstanceProvisionRequestBody.


        :return: The organization_guid of this ServiceInstanceProvisionRequestBody.
        :rtype: str
        """
        return self._organization_guid

    @organization_guid.setter
    def organization_guid(self, organization_guid: str):
        """Sets the organization_guid of this ServiceInstanceProvisionRequestBody.


        :param organization_guid: The organization_guid of this ServiceInstanceProvisionRequestBody.
        :type organization_guid: str
        """
        if organization_guid is None:
            raise ValueError("Invalid value for `organization_guid`, must not be `None`")  # noqa: E501

        self._organization_guid = organization_guid

    @property
    def space_guid(self) -> str:
        """Gets the space_guid of this ServiceInstanceProvisionRequestBody.


        :return: The space_guid of this ServiceInstanceProvisionRequestBody.
        :rtype: str
        """
        return self._space_guid

    @space_guid.setter
    def space_guid(self, space_guid: str):
        """Sets the space_guid of this ServiceInstanceProvisionRequestBody.


        :param space_guid: The space_guid of this ServiceInstanceProvisionRequestBody.
        :type space_guid: str
        """
        if space_guid is None:
            raise ValueError("Invalid value for `space_guid`, must not be `None`")  # noqa: E501

        self._space_guid = space_guid

    @property
    def parameters(self) -> Object:
        """Gets the parameters of this ServiceInstanceProvisionRequestBody.


        :return: The parameters of this ServiceInstanceProvisionRequestBody.
        :rtype: Object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: Object):
        """Sets the parameters of this ServiceInstanceProvisionRequestBody.


        :param parameters: The parameters of this ServiceInstanceProvisionRequestBody.
        :type parameters: Object
        """

        self._parameters = parameters
