# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.service_instance_schema_create import ServiceInstanceSchemaCreate  # noqa: F401,E501
from swagger_server import util


class ServiceInstanceSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, create: ServiceInstanceSchemaCreate=None, update: ServiceInstanceSchemaCreate=None):  # noqa: E501
        """ServiceInstanceSchema - a model defined in Swagger

        :param create: The create of this ServiceInstanceSchema.  # noqa: E501
        :type create: ServiceInstanceSchemaCreate
        :param update: The update of this ServiceInstanceSchema.  # noqa: E501
        :type update: ServiceInstanceSchemaCreate
        """
        self.swagger_types = {
            'create': ServiceInstanceSchemaCreate,
            'update': ServiceInstanceSchemaCreate
        }

        self.attribute_map = {
            'create': 'create',
            'update': 'update'
        }
        self._create = create
        self._update = update

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceInstanceSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceInstanceSchema of this ServiceInstanceSchema.  # noqa: E501
        :rtype: ServiceInstanceSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def create(self) -> ServiceInstanceSchemaCreate:
        """Gets the create of this ServiceInstanceSchema.


        :return: The create of this ServiceInstanceSchema.
        :rtype: ServiceInstanceSchemaCreate
        """
        return self._create

    @create.setter
    def create(self, create: ServiceInstanceSchemaCreate):
        """Sets the create of this ServiceInstanceSchema.


        :param create: The create of this ServiceInstanceSchema.
        :type create: ServiceInstanceSchemaCreate
        """

        self._create = create

    @property
    def update(self) -> ServiceInstanceSchemaCreate:
        """Gets the update of this ServiceInstanceSchema.


        :return: The update of this ServiceInstanceSchema.
        :rtype: ServiceInstanceSchemaCreate
        """
        return self._update

    @update.setter
    def update(self, update: ServiceInstanceSchemaCreate):
        """Sets the update of this ServiceInstanceSchema.


        :param update: The update of this ServiceInstanceSchema.
        :type update: ServiceInstanceSchemaCreate
        """

        self._update = update
