# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.service_instance_schema_create import ServiceInstanceSchemaCreate  # noqa: F401,E501
from swagger_server import util


class ServiceBindingSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, create: ServiceInstanceSchemaCreate=None):  # noqa: E501
        """ServiceBindingSchema - a model defined in Swagger

        :param create: The create of this ServiceBindingSchema.  # noqa: E501
        :type create: ServiceInstanceSchemaCreate
        """
        self.swagger_types = {
            'create': ServiceInstanceSchemaCreate
        }

        self.attribute_map = {
            'create': 'create'
        }
        self._create = create

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceBindingSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceBindingSchema of this ServiceBindingSchema.  # noqa: E501
        :rtype: ServiceBindingSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def create(self) -> ServiceInstanceSchemaCreate:
        """Gets the create of this ServiceBindingSchema.


        :return: The create of this ServiceBindingSchema.
        :rtype: ServiceInstanceSchemaCreate
        """
        return self._create

    @create.setter
    def create(self, create: ServiceInstanceSchemaCreate):
        """Sets the create of this ServiceBindingSchema.


        :param create: The create of this ServiceBindingSchema.
        :type create: ServiceInstanceSchemaCreate
        """

        self._create = create
