# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ServiceBindingResouceObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, app_guid: str=None, route: str=None):  # noqa: E501
        """ServiceBindingResouceObject - a model defined in Swagger

        :param app_guid: The app_guid of this ServiceBindingResouceObject.  # noqa: E501
        :type app_guid: str
        :param route: The route of this ServiceBindingResouceObject.  # noqa: E501
        :type route: str
        """
        self.swagger_types = {
            'app_guid': str,
            'route': str
        }

        self.attribute_map = {
            'app_guid': 'app_guid',
            'route': 'route'
        }
        self._app_guid = app_guid
        self._route = route

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceBindingResouceObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceBindingResouceObject of this ServiceBindingResouceObject.  # noqa: E501
        :rtype: ServiceBindingResouceObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def app_guid(self) -> str:
        """Gets the app_guid of this ServiceBindingResouceObject.


        :return: The app_guid of this ServiceBindingResouceObject.
        :rtype: str
        """
        return self._app_guid

    @app_guid.setter
    def app_guid(self, app_guid: str):
        """Sets the app_guid of this ServiceBindingResouceObject.


        :param app_guid: The app_guid of this ServiceBindingResouceObject.
        :type app_guid: str
        """

        self._app_guid = app_guid

    @property
    def route(self) -> str:
        """Gets the route of this ServiceBindingResouceObject.


        :return: The route of this ServiceBindingResouceObject.
        :rtype: str
        """
        return self._route

    @route.setter
    def route(self, route: str):
        """Sets the route of this ServiceBindingResouceObject.


        :param route: The route of this ServiceBindingResouceObject.
        :type route: str
        """

        self._route = route
