# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ServiceInstanceSchemaCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, parameters: object=None):  # noqa: E501
        """ServiceInstanceSchemaCreate - a model defined in Swagger

        :param parameters: The parameters of this ServiceInstanceSchemaCreate.  # noqa: E501
        :type parameters: object
        """
        self.swagger_types = {
            'parameters': object
        }

        self.attribute_map = {
            'parameters': 'parameters'
        }
        self._parameters = parameters

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceInstanceSchemaCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceInstanceSchema_create of this ServiceInstanceSchemaCreate.  # noqa: E501
        :rtype: ServiceInstanceSchemaCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def parameters(self) -> object:
        """Gets the parameters of this ServiceInstanceSchemaCreate.


        :return: The parameters of this ServiceInstanceSchemaCreate.
        :rtype: object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: object):
        """Sets the parameters of this ServiceInstanceSchemaCreate.


        :param parameters: The parameters of this ServiceInstanceSchemaCreate.
        :type parameters: object
        """

        self._parameters = parameters
